[[language]]
name = "bash"
file-types = ["sh", "bash", "zsh", ".bash_login", ".bash_logout", ".bash_profile", ".bashrc", ".profile", ".zshenv", ".zlogin", ".zlogout", ".zprofile", ".zshrc", "APKBUILD", "PKGBUILD", "eclass", "ebuild", "bazelrc", ".env"]


[[language]]
name = "rust"
config = { checkOnSave = { command = "clippy" } }


[[language]]
name = "dockerfile"
indent = { tab-width = 4, unit = "    " }
