user:
    hashedPassword: ENC[AES256_GCM,data:UqNKMQZGo7VlveDUqjPR8mN0zjmr+pT1OSjMj3Ei83hWR2CXCmue4y/bHLvH+kSeme4dQoz8lGC+7phE0VZnsvSzdmrFOrqxVA==,iv:lVercc3ECuC/dbgU9pm3Pa7a1usZcjD2EbeFJJ3hPw4=,tag:MaBOLrIJE2T1SPCmsfNdOw==,type:str]
backup:
    pve:
        repository-password: ENC[AES256_GCM,data:m9ZGDUhh7JEvVFaIb281fwBKBa8M+8EcQ16nzHhdnEqFNzDe49V8J+ZGMFmUA3pzyiRvuewlSgYJNjlVzJpnxw==,iv:/3IuOCvcfhLTRvrWnlNVFxtJtLHynNX2j245Rg5uej8=,tag:xjJ+ErunDZ3KX1fl1nwY8g==,type:str]
        rest-password: ENC[AES256_GCM,data:IlYdwcl1ZhM6gBNH+nQgtvbAIZImO3X9RW1YHkD4W5mFyrTdrAKjwLaZJWVNChnTWrau+uhIQfOnUPCaUtuUNw==,iv:sItp4Xy+eOk5NuIARXUr9U7fKfI7F0BYrsJN+Msmims=,tag:W3zlnAm5EzM/PmW8Obngxw==,type:str]
    home:
        repository-password: ENC[AES256_GCM,data:pCZaYwgXATWOysmwF4/UU6OwJgumWxnJeh3aIExSpreIzthDEgwinMyVOhpUo9NfxdIdQOpCW0JcaUdmIF+Ogg==,iv:Op++W7T0VvYzH38Iip8cFffZxL/6C3yrUA204jx7cEc=,tag:ZIvDjVCId7/gOCpVPA3gdg==,type:str]
        rest-password: ENC[AES256_GCM,data:AkmcWqWDkbpsX4i4FOIi2N/UhPNNVr56/qsgXjRxp9ut6D2zyznbokyJO3uwsbM5wk0y4VeqjIJwV9++A60lXw==,iv:tNwuslThgxWZgpF7OwLx0v6pnsGtKLCZYKu4ZFsI1vU=,tag:Sg31L4eTMeXPorx3G8bhrQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12qr4rxqrrr59fa9fqtvk0jtf9hsynv3jf5xgjj3fdczujrz65paqh6qc8g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkLzZxaVNZZWR5UEZpLzA3
            b01qVW1UNkdxbHVZQjBDRGhlRHRiWXk5WUFvCm9nSVhhMExENklYNmwwN2w2RUZy
            ejRzYU5BODhUUWtpOTBsQ0I3S3FwYzQKLS0tIGk5MmdFblh3RjBMbGJrNnJkSDRK
            anNjS1E0M3lZekFveFdoblFkcnBMKzAKZeXoj7jHWeWllwPGV7UvoFk0Wc/oCo8o
            Sa4anpi03Gu0kONwP6bQWWlr+2+zHjS6vizZgAWmk4dbpgVgeRA01Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-18T09:10:24Z"
    mac: ENC[AES256_GCM,data:Z+qQj0IRS4bG7zbhLuvuMOX1vMDHLrC5YGAnvpehq6OaLvfxbNzy0uWG6LzJwlSkvRcwbNY64ujMwCswQ0HW7h1mpVVeCqXYfbMlj5jos1WcfMEe7CqE2rvg585K8oaIcht32StlsMlY2JTiwXNC4RTYAX8BQI8qOyOFh80zh7Q=,iv:0deYVXnUErNLMmPHv1bAvDqI/bM+MiZ83FzzKkORxG8=,tag:Tb3j/auRr1QqyTCo3/xabQ==,type:str]
    pgp:
        - created_at: "2023-08-05T14:48:19Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wV4D8w/Zb+cfdxsSAQdAq7+v7y5g8lhGR0MuQXmEjVeJbUtew9v5zYuWzkOy8RMw
            rPZrMDFuHwnBjsCtwAflgZ6TljXEctb/+PvWwbg+mncCwn6w0Eof++n/G4VzfZyx
            0lEB2/9x0qyQjOptKTHXm64ScVufU3kdkNfSyIDN/vPuEcpSCmDuaZ8+J9XdjR/N
            tIuBvDQsT03fMzF5Y+GKwUN26j/ZYu2kVPpF22xxN4pkVrc=
            =zBDW
            -----END PGP MESSAGE-----
          fp: 61303BBAD7D1BF74EFA44E3BE7FE2087E4380E64
    unencrypted_suffix: _unencrypted
    version: 3.8.1
