user:
    hashedPassword: ENC[AES256_GCM,data:UqNKMQZGo7VlveDUqjPR8mN0zjmr+pT1OSjMj3Ei83hWR2CXCmue4y/bHLvH+kSeme4dQoz8lGC+7phE0VZnsvSzdmrFOrqxVA==,iv:lVercc3ECuC/dbgU9pm3Pa7a1usZcjD2EbeFJJ3hPw4=,tag:MaBOLrIJE2T1SPCmsfNdOw==,type:str]
backup:
    srv:
        repository-password: ENC[AES256_GCM,data:BwCZh8xIBseTL25RFFy4r9eluMfEb3Z7L0POU+7UZvXPC6x2d1GgrKwqQ6532rOzawp8d0KiRHQynVL781Onuw==,iv:7CtdDCRJdZcLkwEbLKBdpO9Lwv2W8fhXI7MPRyMWOqQ=,tag:TSSqVmdapZkpuCcf1iOJvA==,type:str]
        rest-password: ENC[AES256_GCM,data:yHJr8hFagoOAIgWP2LMULk5sD3Unf6vWlSCdOb2TIWNrmCgZFdKij4nGpjdvKfyasi8Nz1zwh0hJUP3ZmCn8Pw==,iv:SIKUAOK6PCUCBl8mlUGP85iDNK8GapZGlF7jgGX6P7A=,tag:Spgs1MztlSx3JtdcPyvceQ==,type:str]
    home:
        repository-password: ENC[AES256_GCM,data:pCZaYwgXATWOysmwF4/UU6OwJgumWxnJeh3aIExSpreIzthDEgwinMyVOhpUo9NfxdIdQOpCW0JcaUdmIF+Ogg==,iv:Op++W7T0VvYzH38Iip8cFffZxL/6C3yrUA204jx7cEc=,tag:ZIvDjVCId7/gOCpVPA3gdg==,type:str]
        rest-password: ENC[AES256_GCM,data:AkmcWqWDkbpsX4i4FOIi2N/UhPNNVr56/qsgXjRxp9ut6D2zyznbokyJO3uwsbM5wk0y4VeqjIJwV9++A60lXw==,iv:tNwuslThgxWZgpF7OwLx0v6pnsGtKLCZYKu4ZFsI1vU=,tag:Sg31L4eTMeXPorx3G8bhrQ==,type:str]
    box:
        repository-password: ENC[AES256_GCM,data:pwJzMk+AINzeJ020d+QGcKzTh0Ri39Oi3T5UhKZ1gntOZkEImBaHjut/UeYp1/o1xEhtrOEgoZf3xHKW1VXNbg==,iv:xP1L/KzRXzSIZApGSyOMb3Wzk7gre13WQz90qJYN53I=,tag:EqHfOSnzLNAqY+hSyf6sNg==,type:str]
        ssh-key: ENC[AES256_GCM,data:qeu8kRkjAbp2pjcvReZO3lQ+yzN9oM7Mjw/Ijd9hA3kfCo29rgJNtAbUoMnm1GUpMhGEH83zqCteCPvBL4vjz8ZGw893wuKxxIy1TFjq2QhRpx9cZ+ws4TpE1Aqx7RDElOR6uGvc212Be++5aDwQ0J4ThrJSl1xKefRRfna7FZFlZiLcnfWvv6aO1U39tIpcmoMCjlWcY0afQTsCFVfxrtt7Bw4A71IZYVs9eHkGcurCeX7w810IKAIRP7bgicVLwUFDKaF6awxs4oFGesQi2WcTZspsUxxPeagH5sfEDR2gobAfGLcI0h40eHl7zW5b0WPpGt4Dy8AzxbNJw+ppN1Az0HgDZ/xA0CuU8GPiyWKAHcneQ4qIIgqjGz910ShX5xcTvP/vL6RozxCAjdzlTC3hmFBfLEIm2kWsu8CsIW9Rtw8gPd/8Wkr2SlmUiPivjCtqIJN+/8VbiUTVByhhGJQ22t8F6at2ZKdA9Scms6VYFPELlpllD9l0+qf3duxBbR2G,iv:jCKJiatdmkr3tExp1yazyoFqftPEMQzG7n4OTbv60cY=,tag:HAEvcYJBty9pd82mIGyYsQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12qr4rxqrrr59fa9fqtvk0jtf9hsynv3jf5xgjj3fdczujrz65paqh6qc8g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkLzZxaVNZZWR5UEZpLzA3
            b01qVW1UNkdxbHVZQjBDRGhlRHRiWXk5WUFvCm9nSVhhMExENklYNmwwN2w2RUZy
            ejRzYU5BODhUUWtpOTBsQ0I3S3FwYzQKLS0tIGk5MmdFblh3RjBMbGJrNnJkSDRK
            anNjS1E0M3lZekFveFdoblFkcnBMKzAKZeXoj7jHWeWllwPGV7UvoFk0Wc/oCo8o
            Sa4anpi03Gu0kONwP6bQWWlr+2+zHjS6vizZgAWmk4dbpgVgeRA01Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-15T13:12:24Z"
    mac: ENC[AES256_GCM,data:7TiKuTBrjaxUzwx0tJPnN0MB/kyNNWDBtHdeGtgfGHlFVqxc37xRABC2brkujxAZzxMNU05GyJ5dBD9WKhLVDN3nAuadIUPjLrJoOhsWLt6nX7mtO1oangrMTeNwqVDS7Xcbo9n4BvLICvdxK8vw+JcuoHqew2WjvwCDjW8Eu4Y=,iv:I2T1s9rfanD/lGP5gHP6yqGFzvyrF1HJ4vaj/jetjNE=,tag:uOp+4bq2QzLE5SGfuxMWRA==,type:str]
    pgp:
        - created_at: "2023-08-05T14:48:19Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wV4D8w/Zb+cfdxsSAQdAq7+v7y5g8lhGR0MuQXmEjVeJbUtew9v5zYuWzkOy8RMw
            rPZrMDFuHwnBjsCtwAflgZ6TljXEctb/+PvWwbg+mncCwn6w0Eof++n/G4VzfZyx
            0lEB2/9x0qyQjOptKTHXm64ScVufU3kdkNfSyIDN/vPuEcpSCmDuaZ8+J9XdjR/N
            tIuBvDQsT03fMzF5Y+GKwUN26j/ZYu2kVPpF22xxN4pkVrc=
            =zBDW
            -----END PGP MESSAGE-----
          fp: 61303BBAD7D1BF74EFA44E3BE7FE2087E4380E64
    unencrypted_suffix: _unencrypted
    version: 3.9.0
