user:
    hashedPassword: ENC[AES256_GCM,data:UqNKMQZGo7VlveDUqjPR8mN0zjmr+pT1OSjMj3Ei83hWR2CXCmue4y/bHLvH+kSeme4dQoz8lGC+7phE0VZnsvSzdmrFOrqxVA==,iv:lVercc3ECuC/dbgU9pm3Pa7a1usZcjD2EbeFJJ3hPw4=,tag:MaBOLrIJE2T1SPCmsfNdOw==,type:str]
borg:
    ssh_key: ENC[AES256_GCM,data:ms4kiTMWhV3NpeKxbUUSk64f+f6m/hkgoxLnGC8wh2J4LY9X1dblcw8b3hhwOrXjTSQPpilAqXRLisd7VC7/U6glIuA+rBWWG/IFznXvoPqo4LkRsblHcer3lNY90Qg5RvlhUnV+x2dgc4falzDjcwPd437LkhJsJXG0mxaqy49vg2xVcKPTJhjiV/BKJw/es+k+0alsyxL6Jk9YLiC0OIHJF8PIsbKuW38DBwwWc8i2ptB89UH8oP/Kv/lMJpF2WFhdF83wXZcyt99z2HjqMdxrbULrpwwdVNqOvJ0RV6lc0MLFOtHW64Aydax3+IfatwZeUPJs2JUr2f6Q1nOvAmaUbvE+SEluvq4VIFsBqvRNap+w1i/ghnAL8O4ivCgOpsajkU1jHdVtT8CtXfRXCki4fRFL57Ve7QYPdJVfDRe92tkAoda9UaOv6YzPSAri5vISoFsdfhx6QILwd1xvsgtSuQOwKFJ4Sab2JnOAl/+YHj3Cp0p8sr4do1oNezmC9dle,iv:BvKBJi/ogjugL/94BPbuaLmAtTDhIpLU2MSM2yrkzNg=,tag:zqnDC5K5OFP3TWNAow5shw==,type:str]
    encryption_key: ENC[AES256_GCM,data:Ly2+SGKzamuXUQBJ4JQAmIj4O16va1O1wjTEPtfU5bmyci/LukJvINJXIZ7fGj8qaq3qD+tmeGgdniLXSNplo8MGMIuAU+3UpPg5xrNy0vBXBAcd/VBj+UcibZJGzTi+AGRZIz7MwGyxTgDJccm7TD1YlvxOhhgKKo99s4aReWY=,iv:1aHtgPZQq/qbA2jw3v3wpKULdrgQ3WX8+leU0+qjQHI=,tag:kTGlDSDQJQ+AbgS5ASP0hA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12qr4rxqrrr59fa9fqtvk0jtf9hsynv3jf5xgjj3fdczujrz65paqh6qc8g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkLzZxaVNZZWR5UEZpLzA3
            b01qVW1UNkdxbHVZQjBDRGhlRHRiWXk5WUFvCm9nSVhhMExENklYNmwwN2w2RUZy
            ejRzYU5BODhUUWtpOTBsQ0I3S3FwYzQKLS0tIGk5MmdFblh3RjBMbGJrNnJkSDRK
            anNjS1E0M3lZekFveFdoblFkcnBMKzAKZeXoj7jHWeWllwPGV7UvoFk0Wc/oCo8o
            Sa4anpi03Gu0kONwP6bQWWlr+2+zHjS6vizZgAWmk4dbpgVgeRA01Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-05T15:19:40Z"
    mac: ENC[AES256_GCM,data:YK15Ic7eierDWiC3taXfRwdJcWoX1hqfA7lZKkuAPKFVWPRprXUob8wT/M2kfLOnErIBbeDkZf6P8leXt2jCNhNwo4GlZXMDmIAdtpjmXS5UAHy1hRrOjm0khTiUqZkS7eXD338d8YLGPz0+PRpwkvA+LVbr2Imdg7x4C8UKkIY=,iv:yfs/bmcEb25KNijN56VlXrabkWOEkVN3CyXuPMO7tZY=,tag:nhPZ7k3Lhj4Qw+cjDLarmg==,type:str]
    pgp:
        - created_at: "2023-08-05T14:48:19Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wV4D8w/Zb+cfdxsSAQdAq7+v7y5g8lhGR0MuQXmEjVeJbUtew9v5zYuWzkOy8RMw
            rPZrMDFuHwnBjsCtwAflgZ6TljXEctb/+PvWwbg+mncCwn6w0Eof++n/G4VzfZyx
            0lEB2/9x0qyQjOptKTHXm64ScVufU3kdkNfSyIDN/vPuEcpSCmDuaZ8+J9XdjR/N
            tIuBvDQsT03fMzF5Y+GKwUN26j/ZYu2kVPpF22xxN4pkVrc=
            =zBDW
            -----END PGP MESSAGE-----
          fp: 61303BBAD7D1BF74EFA44E3BE7FE2087E4380E64
    unencrypted_suffix: _unencrypted
    version: 3.7.3
