user:
    hashedPassword: ENC[AES256_GCM,data:UqNKMQZGo7VlveDUqjPR8mN0zjmr+pT1OSjMj3Ei83hWR2CXCmue4y/bHLvH+kSeme4dQoz8lGC+7phE0VZnsvSzdmrFOrqxVA==,iv:lVercc3ECuC/dbgU9pm3Pa7a1usZcjD2EbeFJJ3hPw4=,tag:MaBOLrIJE2T1SPCmsfNdOw==,type:str]
borg:
    ssh_key: ENC[AES256_GCM,data:ms4kiTMWhV3NpeKxbUUSk64f+f6m/hkgoxLnGC8wh2J4LY9X1dblcw8b3hhwOrXjTSQPpilAqXRLisd7VC7/U6glIuA+rBWWG/IFznXvoPqo4LkRsblHcer3lNY90Qg5RvlhUnV+x2dgc4falzDjcwPd437LkhJsJXG0mxaqy49vg2xVcKPTJhjiV/BKJw/es+k+0alsyxL6Jk9YLiC0OIHJF8PIsbKuW38DBwwWc8i2ptB89UH8oP/Kv/lMJpF2WFhdF83wXZcyt99z2HjqMdxrbULrpwwdVNqOvJ0RV6lc0MLFOtHW64Aydax3+IfatwZeUPJs2JUr2f6Q1nOvAmaUbvE+SEluvq4VIFsBqvRNap+w1i/ghnAL8O4ivCgOpsajkU1jHdVtT8CtXfRXCki4fRFL57Ve7QYPdJVfDRe92tkAoda9UaOv6YzPSAri5vISoFsdfhx6QILwd1xvsgtSuQOwKFJ4Sab2JnOAl/+YHj3Cp0p8sr4do1oNezmC9dle,iv:BvKBJi/ogjugL/94BPbuaLmAtTDhIpLU2MSM2yrkzNg=,tag:zqnDC5K5OFP3TWNAow5shw==,type:str]
    encryption_key: ENC[AES256_GCM,data:Ly2+SGKzamuXUQBJ4JQAmIj4O16va1O1wjTEPtfU5bmyci/LukJvINJXIZ7fGj8qaq3qD+tmeGgdniLXSNplo8MGMIuAU+3UpPg5xrNy0vBXBAcd/VBj+UcibZJGzTi+AGRZIz7MwGyxTgDJccm7TD1YlvxOhhgKKo99s4aReWY=,iv:1aHtgPZQq/qbA2jw3v3wpKULdrgQ3WX8+leU0+qjQHI=,tag:kTGlDSDQJQ+AbgS5ASP0hA==,type:str]
btrbk:
    box:
        ssh_key: ENC[AES256_GCM,data:IUAXFfRyKjtlgwNymnSzUQL4kdtRU9teYqb2zT7Kj+YiJzEo8TjiCz3e8C89ykVHRc8E2gIhGTm2QsuLrUH9lalQDiKIChLFsRYYRtOH0OOdodQS0z2vzp7DtH7Yl3omKYjjXTS78pOnmU5QqMJI6TVaXi7w5Z3+4ry/W4Oe6H9UOligJrSEb1Z5jf27AjDDTcUVBurUHkIwLRpQsNaN/7ULjoyaLKzpBAnn+4GnjCGasePWRs4coSQAlzQyydG+1XMu9l3PdG6/ClemtnMOOokU6dE03ehs+/PMwS7ESDKfEa5UNivoprjRPKkSLXBT1RQS2tIYe8McE92ih73UhUxNHsRY7BBgPn1k6aFYlJLzqkTN527oZL3xgNOhG2kKuZ4NDZRSmw0uwfyJZJjjGBAmwODZfOXoDgYLcczpCACICrUVsalHy1ir8KqPvDo4e3/nfwXLd4+6l16Jo6kUelzCcgxSb/ELrjXwwwyFdi3yB8IMrsRDd0P9sWS3ZCZld9OM,iv:VGaLbFL/k6nKw0TU0AhwBrXqldw8AWLxoTsrZWtxp8E=,tag:9RUqnhMr8HwqL6I86Fgzuw==,type:str]
        encryption_key: ENC[AES256_GCM,data:BAa9525DX2U8Ae7YDKgG9u6jvnK5hCG/Gu9FSZcriBw2VHUGtTrnZAWmyvM5MgVXKRpyKbDvBkylQbpvzmsuhm3URMSGSQ3Gqet3r1L+U70du05pO2/7i+ujDKWXtzA2hPrZV2swUny1BBVtQMqDq9BtBffygP0zUGycriWA2rM=,iv:vOU7ajEAHpsqCZE18VPTAfPJ2np5lmLYU+cP9jwIQBo=,tag:gHsHlCL4Hg6GuVkKq2aG3g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12qr4rxqrrr59fa9fqtvk0jtf9hsynv3jf5xgjj3fdczujrz65paqh6qc8g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkLzZxaVNZZWR5UEZpLzA3
            b01qVW1UNkdxbHVZQjBDRGhlRHRiWXk5WUFvCm9nSVhhMExENklYNmwwN2w2RUZy
            ejRzYU5BODhUUWtpOTBsQ0I3S3FwYzQKLS0tIGk5MmdFblh3RjBMbGJrNnJkSDRK
            anNjS1E0M3lZekFveFdoblFkcnBMKzAKZeXoj7jHWeWllwPGV7UvoFk0Wc/oCo8o
            Sa4anpi03Gu0kONwP6bQWWlr+2+zHjS6vizZgAWmk4dbpgVgeRA01Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-25T18:33:07Z"
    mac: ENC[AES256_GCM,data:pySlFtE2HIyqOA5hB5fT0+TI0p2wMN58Ioyhl4gEz7UkaOiZaGG16hTS5cDjvabL3H35B6czeQZq2KLzR8YmpYzzYX7fBNUWrR05gm60uRpUQvToJf+1VIOqwi7cXFnHF4lCNUXPRWLto6BgqVWZ03JGsVs+ulX6ZSkjCXeDNis=,iv:8GwFtPsQVFb4RHNb1pMgIUrmfxBfzx1gbzRH9uILZ5k=,tag:Sp3LpDpGTOaDRC6Xv+mYfg==,type:str]
    pgp:
        - created_at: "2023-08-05T14:48:19Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wV4D8w/Zb+cfdxsSAQdAq7+v7y5g8lhGR0MuQXmEjVeJbUtew9v5zYuWzkOy8RMw
            rPZrMDFuHwnBjsCtwAflgZ6TljXEctb/+PvWwbg+mncCwn6w0Eof++n/G4VzfZyx
            0lEB2/9x0qyQjOptKTHXm64ScVufU3kdkNfSyIDN/vPuEcpSCmDuaZ8+J9XdjR/N
            tIuBvDQsT03fMzF5Y+GKwUN26j/ZYu2kVPpF22xxN4pkVrc=
            =zBDW
            -----END PGP MESSAGE-----
          fp: 61303BBAD7D1BF74EFA44E3BE7FE2087E4380E64
    unencrypted_suffix: _unencrypted
    version: 3.8.1
