includes = []

packages = [
    # cli
    "vim", "tmux", "zsh", "p10k", "profile", "scripts", "vifm", "pbincli", "ssh", "helix", "git",

    # gui
    "x11", "icons", "wallpapers", "i3", "compton", "polybar", "rofi", "fonts", "dunst", "redshift",

    # applications
    "xournalpp", "code", "alacritty",
]

[files]

[variables]
enc = false

# zsh
[variables.zsh]
temptex = true

# vim
[variables.vim.plugins]
airline = true
nginx = true
vimtex = true
vim-nix = true
vim-svelte = true

# st
[variables.st]
fontsize = 10
alpha = 0.90

# profile
[variables.profile]
auto_start = ""

# i3
[variables.i3]
clipman = true
autotiling = false

# polybar
[variables.polybar.modules]
screenshot = false
rofi = false
updates = true
restart = true

[variables.polybar.battery]
full-at = 95

[variables.git]
delta = true

[variables.alacritty]
font.size = 9.5
opacity = 0.8
