networking:
    vpn:
        default: ENC[AES256_GCM,data:lHNrKItspeLlCjMM+AzsaLAOxXANk9bWUi9MR/sV35izw37g,iv:g4sd8yQHTxnZd9UqZBaShURw14QlRwyLgCMc7Pt3E3Y=,tag:1kE+ADDLE3oAZ1+Fx3O6YQ==,type:str]
        full: ENC[AES256_GCM,data:jhL4fky6AFE/M/tyyP5i/hRYMix3u2SBJgByVr7LLBqQwT/c,iv:voPs/5BhudCyA80XMe7z5tkZ39MuXdtRJnNi3MYGPP8=,tag:mEwBbzKh8BdaX1K91WobuQ==,type:str]
    wifi:
        trusted: ENC[AES256_GCM,data:CN54o6avZUMlECJsAGBHzQvpOT0bWBXHnvlEazkckdFE5l0vYZmyFmb9FEyF/hGRpBkyleWapIzbJTSGKYeuL+7F5rIEXGGheHU=,iv:T8D4P9wBnhnq3mcjUKMl74zbB+X36iGmNorNaOy+crc=,tag:PZ4hUmGrv74332BgWhf1tQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v9szwgk0xp383z9fu657kzp60mpxlsg4lm0c73xest7xdrcf4qnqfwlnrd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvZGJ3cmRHeHlnd3JTT0l0
            c25lUjMxNzRCRklRa2dBUWJNY2o0YTNzakY0Clo2SkVTUEVkeVBVVFhQUnozWm9l
            dUU2QzJ4ZHBYWXRIOFhOS1NCYmtON0UKLS0tIDQxM2hqdlVBWStXOGpSU3FtM3ds
            MU1nc3YxeHRFZXlMRWNWNmlBaklaMVkK2/ODGJfsiK1vaMVtnqKbBlO5Wld3VhQ9
            qBfPQef94N2wvKl3jY8h2msdsDLgQ2HAoAfNAGrh+y4yY9N5ekG9ZA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age12qr4rxqrrr59fa9fqtvk0jtf9hsynv3jf5xgjj3fdczujrz65paqh6qc8g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEc2JKWUpYZXB3a0pPUFhY
            UklzdmxqQnBlTlVGN1ZEL2hjdXNxZlFoNFN3Ck1NNDM2T0xkdHpRNTlZUnl6Z2Ja
            cC8xOWs2b29YWlVYdDl2Y3MvV054OWMKLS0tIDMxMUdad1RBbkk4QXk0N2Z4OGw2
            WGg2RWZZSjBzdVRCMTYvRXVpd25MdmcKv3T4je9iRBmN6pqkfcTb1E3j0yY5q7Fm
            5vZBV+YMJe8tVYiv7c+KJu2BFZ/PpbSzW2sFWCdxNghIKn46bm3IdA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-05T20:43:07Z"
    mac: ENC[AES256_GCM,data:849PRf1MrieA9OYJaHBgqkwCnAxJYeqcfg1ruekgAY9oBM/j0TjuG9diBaf2yOtpCdpmNF+W5Oaz9h55LP4ID2jJbceUcLLZ5XGZgXwVA6jN5ZkIU89XixL24bBbHV1CWKAjpl7k9DNboazRRUjWNo+S7flVcdIyzClCO4dx9ec=,iv:MXccjZemAck1NGMxSsOxwO7ih1AZZSMCOYxzBICC14U=,tag:Hbl0ZwZ2DP4m/7BER1n9CA==,type:str]
    pgp:
        - created_at: "2023-06-14T22:07:18Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wV4D8w/Zb+cfdxsSAQdArsZgztSwhPXO+Se0NZ6VHad9rVzao9xKQynyQtFligQw
            d3iqfj4ElMj9EZgPW/S9pDJzopdaEc0/JO/ptFBDrucf5eHmSKrbRVEhCJmXyfiB
            0lEBa6pUtAoKHm+qp1fWxIN4buEt4YJPEFziy0qQCJSfm8RXYP3PvQngGQ7DYnxo
            zGnMDk/jugYZryYxQj9UL2MJlkXZ0Rf5TWZzILsRXrS3Aw4=
            =IVJW
            -----END PGP MESSAGE-----
          fp: 61303BBAD7D1BF74EFA44E3BE7FE2087E4380E64
    unencrypted_suffix: _unencrypted
    version: 3.7.3
