foo: ENC[AES256_GCM,data:O+cs,iv:wFzfuXAXmUXe+B6gDrO5xrlOsDCjFSmu3yrrPZJIvVs=,tag:0IFANXzphoNQUeyZS1VqbQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v9szwgk0xp383z9fu657kzp60mpxlsg4lm0c73xest7xdrcf4qnqfwlnrd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwSkVHYjg2Mm5PejRmVFhw
            V2xDWWhWQVFzOGhKSWFubU9nMFE5eXQrTUVRClhCSXgvaVpPT0lEUmVWY3d0K0g5
            WW1lV25kNXZ0YlV0Q0E5QWcwMUwrdjQKLS0tIHdjdlkzM2owSWt0VGNtS2FMZ1NO
            MnFDZUt3RFphMHZXTjNlOTlJbFQrVG8K4mo3svY8kQ1Znt0at84aA7vkUi4HAzMY
            h+70UQpjcqMAj7rvnIucnbJJrGJBbK+ylvpPDUT5Vm6kQ8kMS9NtUg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-24T08:41:48Z"
    mac: ENC[AES256_GCM,data:2rqanjJb5FSFWhv/jbmMOt0zTO3gkKnY2TEB4Sq6WGghAF3HyRMFKgtdVu5IiKC3QwGyXQyywWl+fYKU6Yi0pj6EnPh8+qbqTX3TOJXl2ipMbaSFG1Xut28BtbZiMuTRFN8KIZhP0ZSFhRutdHHETLQYwy6ugCyzc7p/LN3M3EY=,iv:l0aWDvVKUaIoijMNsEOYxLcA+MbChpVrXOomBP8MDec=,tag:46HvVLaPiWBNNh1wIsS+9A==,type:str]
    pgp:
        - created_at: "2023-04-24T08:41:43Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wV4D8w/Zb+cfdxsSAQdAdUuG3frrHoARJ6Tf7LfvtdFxo4ad5rZLMAkAnKw+uAEw
            M7eIhXXBJ7nOSdPcEnqcBY2siNg0FsKuM3D+hFhEHop5b03huIuxaPH4xjJyJpMw
            0lEBBj0I/5ZDGP4w7MC1BfjOg3wxBuxzA1Nf9kfdXoUbbtPtNzIfknL9VhVTl+CZ
            U72cVb2qijXz++aM36AON/S1FaqthFAQ71J89LpVLvMrs6s=
            =zgHP
            -----END PGP MESSAGE-----
          fp: 61303BBAD7D1BF74EFA44E3BE7FE2087E4380E64
    unencrypted_suffix: _unencrypted
    version: 3.7.3
