networking:
    vpn:
        default: ENC[AES256_GCM,data:lHNrKItspeLlCjMM+AzsaLAOxXANk9bWUi9MR/sV35izw37g,iv:g4sd8yQHTxnZd9UqZBaShURw14QlRwyLgCMc7Pt3E3Y=,tag:1kE+ADDLE3oAZ1+Fx3O6YQ==,type:str]
        full: ENC[AES256_GCM,data:jhL4fky6AFE/M/tyyP5i/hRYMix3u2SBJgByVr7LLBqQwT/c,iv:voPs/5BhudCyA80XMe7z5tkZ39MuXdtRJnNi3MYGPP8=,tag:mEwBbzKh8BdaX1K91WobuQ==,type:str]
    wifi:
        trusted: ENC[AES256_GCM,data:CN54o6avZUMlECJsAGBHzQvpOT0bWBXHnvlEazkckdFE5l0vYZmyFmb9FEyF/hGRpBkyleWapIzbJTSGKYeuL+7F5rIEXGGheHU=,iv:T8D4P9wBnhnq3mcjUKMl74zbB+X36iGmNorNaOy+crc=,tag:PZ4hUmGrv74332BgWhf1tQ==,type:str]
borg:
    nitrogen:
        borg_repo: ENC[AES256_GCM,data:Z4me85YVzvLb6N7nPhMifVCxOcFtwVBDHjspBHRhrywnr2y+tSGoRw==,iv:M7JBNOueiVzj9+Dd9ZXXox4j/B17Bvgug6LkgsBd2NE=,tag:DSvljQNJ73WkpYrBt2LG5g==,type:str]
        borg_passcommand: ENC[AES256_GCM,data:DOZAjdRTUEz3M1dZwO/Z7IGD1soZJ8Y6y+0lrpZ+8a0qU33WQims8Z4tIcv/BZtBu81dYzJdG58MXS3k1WbHbL5deUJKxpGi+j2LFv8Alw==,iv:Kn+TF4SmoRDce+OM+VrzMgXHelZhMoRdRREhrC9TR2A=,tag:OYw3ZEZwEFZSO2sJjBABMQ==,type:str]
        healthcheck: ENC[AES256_GCM,data:pxpWNN+ULvOlkRwWzf2s7H60xkmeiDtTV+neTpfFFhOzk0qJMGMJrJnWqPsJsJ/b9QplJpn8Z/ZpJfGP2CA=,iv:rmoifzTaK3f45lcBYhRXmYQa9Pl4qrDrdzZayfwQKcs=,tag:R+wBnexOsDjAoht6lbSG/A==,type:str]
        exclude_syncthing: ENC[AES256_GCM,data:7A==,iv:GSE4W3a/QfiNulU4IGmfc2ZncRL2aS4xOpHEBRCx8QU=,tag:iiivrFFQbXFIMddVsmEwFA==,type:str]
    neon:
        borg_repo: ENC[AES256_GCM,data:lPkgE0lRptzYIZb5dKTOpz2OHA/UtxkrGYwM1qwoWKHpJ0Go,iv:9ZsDCNgc/ThMPWhxr8NUwLcxTgx+Xmz8roiztc82/bs=,tag:irqyfr1jjm4s53Oe/nWt6w==,type:str]
        borg_passcommand: ENC[AES256_GCM,data:IXZsyFJp0kI8qwwN6+iaWCihRHi9yOhKfHTZgQIzZ0527tLY0FZ2IiuhA3STY0Wto4yG109ld4ljdT+i1CtecHTBVrvI27KywLQRIwbI2A==,iv:OEJP3TAo6/9NRtUcEy4JnjJ7fCcIwkb/3V0TSAjqTzw=,tag:YauTcpugrC4ldC6l2+pq7w==,type:str]
        healthcheck: ENC[AES256_GCM,data:Jhh51vJGKfKswBEMHhScjE7Unn+KRXK+o5JSWFrRX4nwM6qGYAuPlE7Ch5Y76SXabBcF+gycFlqXnGcTLq0=,iv:hBJOA9RF8WxXCDTVIY01mDn4V1Y1nhKjfA+zHzqxX/A=,tag:FVod/uVNi2iVkKt6YFcKtQ==,type:str]
        exclude_syncthing: ENC[AES256_GCM,data:jA==,iv:hxSEqYeF2X+UKJrRBEelIHsF6mzRZTM9DqFJpaNTw/4=,tag:JKvqcWXrUjuAmIst1YCu6A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v9szwgk0xp383z9fu657kzp60mpxlsg4lm0c73xest7xdrcf4qnqfwlnrd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvZGJ3cmRHeHlnd3JTT0l0
            c25lUjMxNzRCRklRa2dBUWJNY2o0YTNzakY0Clo2SkVTUEVkeVBVVFhQUnozWm9l
            dUU2QzJ4ZHBYWXRIOFhOS1NCYmtON0UKLS0tIDQxM2hqdlVBWStXOGpSU3FtM3ds
            MU1nc3YxeHRFZXlMRWNWNmlBaklaMVkK2/ODGJfsiK1vaMVtnqKbBlO5Wld3VhQ9
            qBfPQef94N2wvKl3jY8h2msdsDLgQ2HAoAfNAGrh+y4yY9N5ekG9ZA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age12qr4rxqrrr59fa9fqtvk0jtf9hsynv3jf5xgjj3fdczujrz65paqh6qc8g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEc2JKWUpYZXB3a0pPUFhY
            UklzdmxqQnBlTlVGN1ZEL2hjdXNxZlFoNFN3Ck1NNDM2T0xkdHpRNTlZUnl6Z2Ja
            cC8xOWs2b29YWlVYdDl2Y3MvV054OWMKLS0tIDMxMUdad1RBbkk4QXk0N2Z4OGw2
            WGg2RWZZSjBzdVRCMTYvRXVpd25MdmcKv3T4je9iRBmN6pqkfcTb1E3j0yY5q7Fm
            5vZBV+YMJe8tVYiv7c+KJu2BFZ/PpbSzW2sFWCdxNghIKn46bm3IdA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-23T15:04:50Z"
    mac: ENC[AES256_GCM,data:VzuuhYWBBHahb4ipPIEg1B7J0vg28/Lfyz5zY58Eg1wHCGRr6T8M7fQvU4K6EstahO1X5NwvDm/lzlai/GFTvzsDsVhiN+1zW4Esgy09GCCgJUPfaakmSfgoVe2n63EPiwJ7yIRQ0kZ4wPZtWm/6TWlznw/7O/+7uRtk0/dfKPY=,iv:8z/5kNX9aAtmEZqrAVSFK/ARwPcBI3bbgRFmRSotOE8=,tag:9kiXu0dgoj3UxwO7Hs7/Vw==,type:str]
    pgp:
        - created_at: "2023-06-14T22:07:18Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wV4D8w/Zb+cfdxsSAQdArsZgztSwhPXO+Se0NZ6VHad9rVzao9xKQynyQtFligQw
            d3iqfj4ElMj9EZgPW/S9pDJzopdaEc0/JO/ptFBDrucf5eHmSKrbRVEhCJmXyfiB
            0lEBa6pUtAoKHm+qp1fWxIN4buEt4YJPEFziy0qQCJSfm8RXYP3PvQngGQ7DYnxo
            zGnMDk/jugYZryYxQj9UL2MJlkXZ0Rf5TWZzILsRXrS3Aw4=
            =IVJW
            -----END PGP MESSAGE-----
          fp: 61303BBAD7D1BF74EFA44E3BE7FE2087E4380E64
    unencrypted_suffix: _unencrypted
    version: 3.7.3
