networking:
    vpn:
        default: ENC[AES256_GCM,data:lHNrKItspeLlCjMM+AzsaLAOxXANk9bWUi9MR/sV35izw37g,iv:g4sd8yQHTxnZd9UqZBaShURw14QlRwyLgCMc7Pt3E3Y=,tag:1kE+ADDLE3oAZ1+Fx3O6YQ==,type:str]
        full: ENC[AES256_GCM,data:jhL4fky6AFE/M/tyyP5i/hRYMix3u2SBJgByVr7LLBqQwT/c,iv:voPs/5BhudCyA80XMe7z5tkZ39MuXdtRJnNi3MYGPP8=,tag:mEwBbzKh8BdaX1K91WobuQ==,type:str]
    wifi:
        trusted: ENC[AES256_GCM,data:ciPtEQSOh+5jTgEPLfgvv3R7mkZS1OfvC6QWHSe0L5c75s9XeQ==,iv:CXOQkWH6MbUAWgOMl9tQmxbaMgDb90D1sHaakU2a+7M=,tag:ze/qJqYxKShGYtekFEPthQ==,type:str]
borg:
    nitrogen:
        borg_repo: ENC[AES256_GCM,data:Z4me85YVzvLb6N7nPhMifVCxOcFtwVBDHjspBHRhrywnr2y+tSGoRw==,iv:M7JBNOueiVzj9+Dd9ZXXox4j/B17Bvgug6LkgsBd2NE=,tag:DSvljQNJ73WkpYrBt2LG5g==,type:str]
        borg_passcommand: ENC[AES256_GCM,data:DOZAjdRTUEz3M1dZwO/Z7IGD1soZJ8Y6y+0lrpZ+8a0qU33WQims8Z4tIcv/BZtBu81dYzJdG58MXS3k1WbHbL5deUJKxpGi+j2LFv8Alw==,iv:Kn+TF4SmoRDce+OM+VrzMgXHelZhMoRdRREhrC9TR2A=,tag:OYw3ZEZwEFZSO2sJjBABMQ==,type:str]
        healthcheck: ENC[AES256_GCM,data:pxpWNN+ULvOlkRwWzf2s7H60xkmeiDtTV+neTpfFFhOzk0qJMGMJrJnWqPsJsJ/b9QplJpn8Z/ZpJfGP2CA=,iv:rmoifzTaK3f45lcBYhRXmYQa9Pl4qrDrdzZayfwQKcs=,tag:R+wBnexOsDjAoht6lbSG/A==,type:str]
        exclude_syncthing: ENC[AES256_GCM,data:7A==,iv:GSE4W3a/QfiNulU4IGmfc2ZncRL2aS4xOpHEBRCx8QU=,tag:iiivrFFQbXFIMddVsmEwFA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v9szwgk0xp383z9fu657kzp60mpxlsg4lm0c73xest7xdrcf4qnqfwlnrd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3SUNIZTh3V2pSclhsUmhL
            cnU3clpOMEk5NHpFOC91cUxSQ3pQcGpOempJClYxUW9LQ0pBZko0bytEWExYQ01S
            cFJJclh6bnc1cDRzbDU1WSs3VEJnREUKLS0tIEdrdWYzV000NXhiUjAxMDJjT3Yy
            WGdqcmc3NUwrdjRES3N4OVliZnM3dVkKdhdG5ihsBoaW/aHNmu+DVEtpUKL1dr34
            3sfN1WAibrG8CXPDP9PJr3lCXd3dS8epgoHuPhePofA6RjlaHmtHpQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-29T22:15:24Z"
    mac: ENC[AES256_GCM,data:oYMlUCp3r8EaEu82kpqXvpjZdIwWqJTNYWjcXOfpfihawS1LNyZqF9QiZDCWt7gAo3pFoCCVjuEQEegZYMiK5Yd/UrJhmsIbOJYimf5nwNmPp8Y6WCifa3Srne/VGHiQDcTxnXvyI2EGHIg6tcDl5S0veV7FCHs1Toxya4nft24=,iv:1tD9ziGCn/VFSMBOizkh8CD0AiiZrdVsi7bcpTaN/L8=,tag:sucE4nQZwSDitvQh98wkyg==,type:str]
    pgp:
        - created_at: "2023-04-29T21:43:11Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wV4D8w/Zb+cfdxsSAQdA80uN9RbAW2YrfU7Qf/2Ik24b7MT+JrPramcULFuvYBow
            m6xp2XXi0eQbQ4djqBUxIens/3LkSNPpGiyuwbGo2wasdcC6Qz6AOgWeqxEvB8Lg
            0lEBEkq43hac66Cc/rf1peNHBZ/kftd3NYeNIgQU/WnLcQ1UX0hIDSFNqNDZ+Pa8
            z+8C3LPPiqDFM3ETKWyn4nsd3suc82wOCtqHY+AoDHFhYXc=
            =qCnt
            -----END PGP MESSAGE-----
          fp: 61303BBAD7D1BF74EFA44E3BE7FE2087E4380E64
    unencrypted_suffix: _unencrypted
    version: 3.7.3
