networking:
    vpn:
        default: ENC[AES256_GCM,data:lHNrKItspeLlCjMM+AzsaLAOxXANk9bWUi9MR/sV35izw37g,iv:g4sd8yQHTxnZd9UqZBaShURw14QlRwyLgCMc7Pt3E3Y=,tag:1kE+ADDLE3oAZ1+Fx3O6YQ==,type:str]
        full: ENC[AES256_GCM,data:jhL4fky6AFE/M/tyyP5i/hRYMix3u2SBJgByVr7LLBqQwT/c,iv:voPs/5BhudCyA80XMe7z5tkZ39MuXdtRJnNi3MYGPP8=,tag:mEwBbzKh8BdaX1K91WobuQ==,type:str]
    wifi:
        trusted: ENC[AES256_GCM,data:CN54o6avZUMlECJsAGBHzQvpOT0bWBXHnvlEazkckdFE5l0vYZmyFmb9FEyF/hGRpBkyleWapIzbJTSGKYeuL+7F5rIEXGGheHU=,iv:T8D4P9wBnhnq3mcjUKMl74zbB+X36iGmNorNaOy+crc=,tag:PZ4hUmGrv74332BgWhf1tQ==,type:str]
borg:
    nitrogen:
        ssh_key: ENC[AES256_GCM,data:hQDV/7qETJnqvF6NW1yT94/6DcKgiP7TbiP9te550KQRUGLtvsXLYLeW1Fhvprov99eOrNAkqBxKnXfrazsMo0mTbYUg3hXXbf5erxWLEKxlv8ChAS5cCGEogJlTWR1rD+wlPs7VXhXCydP3obuPdeFeOCk4g8WDP7nRAwzFCoTL133bpVoZ+mgbqIgMngfBUTynwMOgbIZEun0ExWfJevVfCqOvWqLmzlpcs7RYBh6o8GqkuvW0V5z7aSpsQ9F9lYhRhc7/KDuBezYlis8+rYnttJSd/32mW8gLh5F/aTdjI7X4BE1PPitevmcBlxW5Sh2ScDaGA8GbXkpWgoa2lhW14xXFdAmwfTDiasUJucYOzqIGlDLLqjXgPD8O4xl7gwPgHLFH0ozdnBVC9y2JMsx69VYlpdJlTc+4taaq7Llw0I+a/99t3Gi+DTap21vmN+ohdyEo3+5ungpypbmvz1zgu+zveo9o6oUsAtwfj2S9frlTJYmkP1Tj7DfZAWyfos+2,iv:Yd2vKKJpsffpmExADiGDPKV+cjsKrEuED4Q6N109i2E=,tag:3OrC+IQOVk2IY/HHsOyH7Q==,type:str]
        encryption_key: ENC[AES256_GCM,data:fCCFFXryRXsV6Hv+WFN/1A1yZLWm+bjVhS4URwyQnErGB5s+l/eFH+QIzTrsttzoLRAbGaVvVAwZ2KGTsN9Sv8MWzeYUTWNLKqOvXuvSkOmpaZGRIU+vj1waVY1rHkaoLyLQBtMpZqY9KpPWHKFV07sZfZkOFLiQZES1Hyqy3Qg=,iv:ks4ArN/pckgJvg4xcaXUrKjMs5Rt8UL72BTh9RayFOw=,tag:piX6Ko8eaYDduGSnLBBdLQ==,type:str]
    neon:
        ssh_key: ENC[AES256_GCM,data:xmeKKJ9i7srImiiWA1nfGGFxdmi87ltpUlZFXcB4cCsXe3bCcBucP+q9G+TKDhD1PMQyYiLC86JQLoHP07LotcM+AVS8J9ovKjJNOehFyiRa2cdUJNNHCso1Ds7sRvkWVsmabePJLVw8lVWQ41jwY6yyqH7syRjm/dy4AHgeLndToVycaD5mMQHexfNpdWq7ZLmrruKxORENmuQmiVMsZ1VMTru8yBOCDpjtkiQ+D5WvCUvaoYaVM1FG4UDAMJUcGy9IZI+pj/BlrlRoEIiz/r3go3RKMTMbQC5OBIOcc8xOKNjgQ+dhlLgz10atYbssWJdWIOQMjpTj4La5x1BoRbbACJ6AD7mSuyihJ5jaWpqduFZaUCxMxThy5HT6TMbB+vxwVSXGLduOS1kULtYMIX/enJq6yPzddNwHn8Fny+4huJk9M90/SWz2Zy22Zptc0Ro/cnndfn6TAlbqF55H7f+eO/CTqxDfIYTmlKiTt6vn1QttMNQJ/CcJ+jIGsk5DKHkq,iv:wh11NQvmULhVXBOg4UHvdaYGN6fyp9DR88IJfl8J/lQ=,tag:9plika4IQTdb4quRkhoXBg==,type:str]
        encryption_key: ENC[AES256_GCM,data:FddkzPwNT/BUs9XLowgpOeTErclS1WqXUNJ4IqT9WiBV8sUqggs2O0+93RxKJjNYf/+gk+VdqGn7qLxDs6CgqdeZVG7AuigHMxIBgxxlplgflIiw1Xyh9euEL0WBmvknZylRpRZsmQDffgoSACxgV+zuK3t8j4qqoGSpB0f+F68=,iv:WgsxuXkFAwabUSGzpeNd9occLt5/VJUeUKPHmKCp0x8=,tag:d8nXq1UW4dUyy1PBxO9ThQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v9szwgk0xp383z9fu657kzp60mpxlsg4lm0c73xest7xdrcf4qnqfwlnrd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvZGJ3cmRHeHlnd3JTT0l0
            c25lUjMxNzRCRklRa2dBUWJNY2o0YTNzakY0Clo2SkVTUEVkeVBVVFhQUnozWm9l
            dUU2QzJ4ZHBYWXRIOFhOS1NCYmtON0UKLS0tIDQxM2hqdlVBWStXOGpSU3FtM3ds
            MU1nc3YxeHRFZXlMRWNWNmlBaklaMVkK2/ODGJfsiK1vaMVtnqKbBlO5Wld3VhQ9
            qBfPQef94N2wvKl3jY8h2msdsDLgQ2HAoAfNAGrh+y4yY9N5ekG9ZA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age12qr4rxqrrr59fa9fqtvk0jtf9hsynv3jf5xgjj3fdczujrz65paqh6qc8g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEc2JKWUpYZXB3a0pPUFhY
            UklzdmxqQnBlTlVGN1ZEL2hjdXNxZlFoNFN3Ck1NNDM2T0xkdHpRNTlZUnl6Z2Ja
            cC8xOWs2b29YWlVYdDl2Y3MvV054OWMKLS0tIDMxMUdad1RBbkk4QXk0N2Z4OGw2
            WGg2RWZZSjBzdVRCMTYvRXVpd25MdmcKv3T4je9iRBmN6pqkfcTb1E3j0yY5q7Fm
            5vZBV+YMJe8tVYiv7c+KJu2BFZ/PpbSzW2sFWCdxNghIKn46bm3IdA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-24T16:13:36Z"
    mac: ENC[AES256_GCM,data:2ir3z4Y4gQ/EwtJhXEO5AQ0XaIyXEolwcRR7JzvDfxA7Vuk8PQMeQ32Sx7Ig8LO03vqW+KiLMAm7sEMl0BNHeRic7+mL47Rv/CMzq4Lm7Q6lvChWv4dKLNa3WqD4fd3IaRtVv8TBKBo0nAXVUXRem6VpUq91XdO22U4F1GlgYDU=,iv:iBvJuRzVJnZT2Q3cHibkv2bsJnFqBKxKX0g36vfm2ZM=,tag:vdyIdsjmg5xMzXQynaIheQ==,type:str]
    pgp:
        - created_at: "2023-06-14T22:07:18Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wV4D8w/Zb+cfdxsSAQdArsZgztSwhPXO+Se0NZ6VHad9rVzao9xKQynyQtFligQw
            d3iqfj4ElMj9EZgPW/S9pDJzopdaEc0/JO/ptFBDrucf5eHmSKrbRVEhCJmXyfiB
            0lEBa6pUtAoKHm+qp1fWxIN4buEt4YJPEFziy0qQCJSfm8RXYP3PvQngGQ7DYnxo
            zGnMDk/jugYZryYxQj9UL2MJlkXZ0Rf5TWZzILsRXrS3Aw4=
            =IVJW
            -----END PGP MESSAGE-----
          fp: 61303BBAD7D1BF74EFA44E3BE7FE2087E4380E64
    unencrypted_suffix: _unencrypted
    version: 3.7.3
