networking:
    vpn:
        default: ENC[AES256_GCM,data:lHNrKItspeLlCjMM+AzsaLAOxXANk9bWUi9MR/sV35izw37g,iv:g4sd8yQHTxnZd9UqZBaShURw14QlRwyLgCMc7Pt3E3Y=,tag:1kE+ADDLE3oAZ1+Fx3O6YQ==,type:str]
        full: ENC[AES256_GCM,data:jhL4fky6AFE/M/tyyP5i/hRYMix3u2SBJgByVr7LLBqQwT/c,iv:voPs/5BhudCyA80XMe7z5tkZ39MuXdtRJnNi3MYGPP8=,tag:mEwBbzKh8BdaX1K91WobuQ==,type:str]
    wifi:
        trusted: ENC[AES256_GCM,data:ciPtEQSOh+5jTgEPLfgvv3R7mkZS1OfvC6QWHSe0L5c75s9XeQ==,iv:CXOQkWH6MbUAWgOMl9tQmxbaMgDb90D1sHaakU2a+7M=,tag:ze/qJqYxKShGYtekFEPthQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v9szwgk0xp383z9fu657kzp60mpxlsg4lm0c73xest7xdrcf4qnqfwlnrd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3SUNIZTh3V2pSclhsUmhL
            cnU3clpOMEk5NHpFOC91cUxSQ3pQcGpOempJClYxUW9LQ0pBZko0bytEWExYQ01S
            cFJJclh6bnc1cDRzbDU1WSs3VEJnREUKLS0tIEdrdWYzV000NXhiUjAxMDJjT3Yy
            WGdqcmc3NUwrdjRES3N4OVliZnM3dVkKdhdG5ihsBoaW/aHNmu+DVEtpUKL1dr34
            3sfN1WAibrG8CXPDP9PJr3lCXd3dS8epgoHuPhePofA6RjlaHmtHpQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-29T21:43:11Z"
    mac: ENC[AES256_GCM,data:+71Bzh/NVgV+AuMDJK5O4sgY2FHeu8YFEyW35hhpmZ/bWYCUQYUwyPuX0qs8ho9rOfn9yU4ABL4MAd+8AwUXOSSxVhTq8/3zwnAiwYf0xxx9btrlD8WjB4iyZBENLzrfYiT5PVfcdosdbsYugiVETKm5yYnj6n7WOV8ex7s7oU4=,iv:L1MOHf3fcHyP7+Dh3trd9clPr9mB1M/TLOGuXOUMR8s=,tag:R5Vx4cXEOAIqr7QOiSbYZw==,type:str]
    pgp:
        - created_at: "2023-04-29T21:43:11Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wV4D8w/Zb+cfdxsSAQdA80uN9RbAW2YrfU7Qf/2Ik24b7MT+JrPramcULFuvYBow
            m6xp2XXi0eQbQ4djqBUxIens/3LkSNPpGiyuwbGo2wasdcC6Qz6AOgWeqxEvB8Lg
            0lEBEkq43hac66Cc/rf1peNHBZ/kftd3NYeNIgQU/WnLcQ1UX0hIDSFNqNDZ+Pa8
            z+8C3LPPiqDFM3ETKWyn4nsd3suc82wOCtqHY+AoDHFhYXc=
            =qCnt
            -----END PGP MESSAGE-----
          fp: 61303BBAD7D1BF74EFA44E3BE7FE2087E4380E64
    unencrypted_suffix: _unencrypted
    version: 3.7.3
