user:
    hashedPassword: ENC[AES256_GCM,data:SbCf6FPM7fg36hT03VXZQxePC9S1rVniGp2cT2xJlwBx0vSNLUcZzUbebDPWoTvVN1aDU9H9l7uyOtLFgIB0euPWsK9iauGm0w==,iv:9OsDCHDtWrQccxMqPYg+p8dyrjnfFpJ6NuCWY6LLnpQ=,tag:QezSfsrXyaj31H76wFrgqA==,type:str]
borg:
    ssh_key: ENC[AES256_GCM,data:mlXpTEYW98A3eBZirdFnbb+860ypx4Zyd6xs2sWiMC8HHqIkKu7PBYnVl6j7NTboH6l5vkkqLgAJZRpUIQGkeBMJ0c97jqQOupkgATs6oYlXuqrrnF6F3jY185dYbo4QEp7IJVM/8WHICzDLM61WkwbIhhLgzUJcn3HqmNQBCsFPZCO7WApxBzduglB8hSq+E63aFns7YIXKyVs6ThDu/QJEivYBmaWZWlI2htPbhr2pVCCnLQ1Ka0jPpCws1/ROZN3uUgTnWllPAZkCkvgLVtgikpIzd5ZaoSs7ecE7hMwZoe1wEBHlxEH/ONK4+YKEo2qAVweeO8MI9ZtAqmQ10n0k4hpQ0pdzeP2BGNorx5yGVQntgueT6MRGGwodppvw2AAj9gqmlyT0FjakTVkE/w1Lf/whcBf0lCtpjKAU6fFhZT1hXTmQp6hYaUQkf9bDsYx6txGj+0151+hxZiV8xoxRj51ICJCgM1f0V2yhLeoNKUKsCNrvAH+UqSt3keHhXqh6,iv:mSOli1QwNsXxLlrbIMpJ9TQRzbusfRH4MhyhdDNclOM=,tag:v2yIqG8x2TPaYz50c4sbLw==,type:str]
    encryption_key: ENC[AES256_GCM,data:NMmRDxIuniHpKtYxo3H/BjwshEZLVIHT2oWafhPyDTe5mZ9/gMgYoC41Vp/r6TG5lu+D+Zpuj2o4cOg5m8YqI/PeXMymva+Cz7CQKdWOr5BpWnKIzpfABMA/HTuOd+jfJgXCGnVu6ZjKR3muw2elFiiJhpnyDuag1k2x/xz6t+w=,iv:OeRZfU0ek7QQanxXiR7BEOgCZrC0gDjs6/oXK4lYT/Q=,tag:C9008AeyBBawyZ2895DDhg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v9szwgk0xp383z9fu657kzp60mpxlsg4lm0c73xest7xdrcf4qnqfwlnrd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvVDI0R2UwM2xqcWhMUk1Z
            SjhsVE9hVThlT0FYcDNKUzM4YUttdnJ2WVNJCnhhVU9iZ0FkOG1aUHNxeUxuaW1a
            MVNaSGVoZFdScmpqQ0FnYStKWWgxKzgKLS0tIHBObklDVHEwZFliRDlKNFhrSEp6
            ZEF6VlVZSStQQXlKbjN0UTlXUlpmbzAKX4ijV/OGKO63zRo8s+yg+scIAACwD1za
            4jJoubyGVz+wwgannvZWaRYa8E/WhyBeMO0vgnpN9w57Wf93wgwTlA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-05T20:34:34Z"
    mac: ENC[AES256_GCM,data:KGOsoNpi4I8EtRrkmLUnMzZ4pz/sRPNgT5ctM+PfqNIvi2o+A/bK7J2oR2jqVWeYNf+m6RC4PTvQ8sx7jeS7SjlJNGHplcvaWGqBhy36zQXIRo+pJWfrO6DJp5YL9VwUMBYQHC6QF0IE0eyUm2SIF+4JEeFNsN9a8MOyAzYp9SE=,iv:qKR87eC8gSM3CKta07vF1NKu6gJXaiJWbOAPOJBd4C0=,tag:Qwse3mnrGF3P/w/Rj3KRLg==,type:str]
    pgp:
        - created_at: "2023-08-05T20:33:53Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wV4D8w/Zb+cfdxsSAQdA+mglXEBt1hPKxZ4PEalo2RSMNkCs3Mu6WSwU3+7HuH8w
            FCKXO0aRL8C14qtXKoGsXqvlwFM3/SzRa1JYzIVnavYIb3lV3wUFLA+XOzV8SAzz
            0lEBaUwmuu1ULeIFwYIZ90fYP9SajtlEWW1MYY/ASPAkp5QozZYzFxVNG55BCfDV
            WYGX0PMFh72laKwkIj2StTziBJ2dWRyqLTKeHo5LWKFtAeQ=
            =+Hhu
            -----END PGP MESSAGE-----
          fp: 61303BBAD7D1BF74EFA44E3BE7FE2087E4380E64
    unencrypted_suffix: _unencrypted
    version: 3.7.3
